services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      MARIADB_DATABASE: ${THEREABOUT_DATABASE}
      MARIADB_USER: ${THEREABOUT_DB_USER}
      MARIADB_PASSWORD: ${THEREABOUT_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${THEREABOUT_DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    restart: unless-stopped
    networks:
      - traefik_default
    volumes:
      - thereabout_mariadb:/var/lib/mysql
  thereabout:
    image: 'aerobless/thereabout:latest'
    ports:
      - '9050:9050'
    restart: unless-stopped
    volumes:
      - thereabout_upload:/data
    environment:
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      THEREABOUT_DATABASE: ${THEREABOUT_DATABASE}
      THEREABOUT_DB_USER: ${THEREABOUT_DB_USER}
      THEREABOUT_DB_PASSWORD: ${THEREABOUT_DB_PASSWORD}
      THEREABOUT_ROOT_PASSWORD: ${THEREABOUT_DB_ROOT_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thereabout.rule=Host(`thereabout.your-domain.com`)"
      - "traefik.http.routers.thereabout.entrypoints=websecure"
      - 'traefik.http.routers.thereabout.tls=true'
      - "traefik.http.routers.thereabout.tls.certresolver=myresolver"
      - "traefik.http.routers.thereabout.middlewares=authelia"
      - "traefik.http.routers.thereabout-api.rule=Host(`thereabout.your-domain.com`) && (PathPrefix(`/backend/api/v1/location/geojson`))"
      - "traefik.http.routers.thereabout-api.entrypoints=websecure"
      - 'traefik.http.routers.thereabout-api.tls=true'
      - "traefik.http.routers.thereabout-api.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik_default"

volumes:
  thereabout_upload:
  thereabout_mariadb:

networks:
  traefik_default:
    external: true