import {TestBed} from '@angular/core/testing';
import {Subject} from 'rxjs';
import {CurrentUser, CurrentUserService as CurrentUserApi} from '../../../../generated/backend-api/thereabout';
import {CurrentUserService} from './current-user.service';

describe('CurrentUserService', () => {
  afterEach(() => vi.unstubAllGlobals());
  it('uses the verified target context and restores the actor on exit', () => {
    vi.stubGlobal('location', {hostname: 'localhost'});
    const response = new Subject<CurrentUser>();
    const api = {getCurrentUser: vi.fn(() => response)};
    TestBed.configureTestingModule({providers: [{provide: CurrentUserApi, useValue: api}]});
    const service = TestBed.inject(CurrentUserService);
    service.load(); response.next({status: 'resolved', identityId: 1, role: 'ADMIN', actorRole: 'ADMIN'});
    service.impersonate({id: 3, shortName: 'Group', role: 'USER' as const, isGroup: true});
    service.impersonate({id: 4, shortName: 'Contact', role: null});
    expect(service.impersonatedUser()).toBeNull();
    service.impersonate({id: 2, shortName: 'Heidi', role: 'USER' as const});
    response.next({status: 'resolved', identityId: 2, displayName: 'Heidi', role: 'USER', actorRole: 'ADMIN', impersonating: true});
    expect(service.state()).toMatchObject({status: 'resolved', identityId: 2, displayName: 'Heidi'});
    service.stopImpersonation();
    expect(service.displayName()).toBeUndefined();
    response.next({status: 'resolved', identityId: 1, displayName: 'Theo'});
    expect(service.displayName()).toBe('Theo');
    expect(service.impersonatedUser()).toBeNull();
  });
  it('offers user management to administrators and local development only', () => {
    const response = new Subject<CurrentUser>();
    TestBed.configureTestingModule({providers: [{provide: CurrentUserApi, useValue: {getCurrentUser: vi.fn(() => response)}}]});
    const service = TestBed.inject(CurrentUserService);
    service.load(); response.next({status: 'disabled', role: 'ADMIN', actorRole: 'ADMIN'});
    expect(service.canManageUsers()).toBe(true);
    service.load(); response.next({status: 'resolved', identityId: 2, displayName: 'Heidi', role: 'USER'});
    expect(service.canManageUsers()).toBe(false);
    service.load(); response.next({status: 'resolved', identityId: 1, displayName: 'Admin', role: 'ADMIN'});
    expect(service.canManageUsers()).toBe(true);
  });
  it('retains the view while verifying on return or back-forward restoration', () => {
    const api = {getCurrentUser: vi.fn(() => new Subject<CurrentUser>())};
    TestBed.configureTestingModule({providers: [{provide: CurrentUserApi, useValue: api}]});
    const service = TestBed.inject(CurrentUserService);
    void service.start();
    service.verifiedState.set({status: 'resolved', identityId: 1, displayName: 'Theo'});
    const keys = service.viewKeys();
    const visibility = vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('hidden');
    document.dispatchEvent(new Event('visibilitychange'));
    expect(service.displayName()).toBe('Theo');
    expect(service.viewKeys()).toEqual(keys);
    visibility.mockReturnValue('visible');
    document.dispatchEvent(new Event('visibilitychange'));
    expect(api.getCurrentUser).toHaveBeenCalledTimes(2);
    expect(service.viewKeys()).toEqual(keys);
    window.dispatchEvent(new PageTransitionEvent('pageshow', {persisted: true}));
    expect(api.getCurrentUser).toHaveBeenCalledTimes(3);
    expect(service.viewKeys()).toEqual(keys);
    visibility.mockRestore();
  });
  it('resets the view when background verification finds a new user, permissions or a failure', () => {
    const response = new Subject<CurrentUser>();
    TestBed.configureTestingModule({providers: [{provide: CurrentUserApi, useValue: {getCurrentUser: () => response}}]});
    const service = TestBed.inject(CurrentUserService);
    const admin: CurrentUser = {status: 'resolved', identityId: 1, role: 'ADMIN', actorIdentityId: 1, actorRole: 'ADMIN'};
    service.load(); response.next(admin);
    const keys = service.viewKeys();
    service.load(true); response.next({...admin, displayName: 'Updated name'});
    expect(service.viewKeys()).toEqual(keys);
    response.next({...admin, identityId: 2});
    expect(service.viewKeys()).not.toEqual(keys);
    response.next({...admin, actorRole: 'USER'});
    expect(service.viewKeys()).not.toEqual(keys);
    service.load(true); response.error(new Error('unavailable'));
    expect(service.state().status).toBe('verification_unavailable');
    expect(service.viewKeys()).not.toEqual(keys);
    expect(service.displayName()).toBeUndefined();
  });
  it('clears prior identity on every load, ignores stale requests and distinguishes failures', () => {
    const first = new Subject<CurrentUser>(), second = new Subject<CurrentUser>();
    const api = {getCurrentUser: vi.fn().mockReturnValueOnce(first).mockReturnValueOnce(second)};
    TestBed.configureTestingModule({providers: [{provide: CurrentUserApi, useValue: api}]});
    const service = TestBed.inject(CurrentUserService);
    expect(service.state().status).toBe('loading');
    service.load(); first.next({status: 'resolved', identityId: 1, displayName: 'Theo'});
    expect(service.displayName()).toBe('Theo');
    service.load(); expect(service.displayName()).toBeUndefined();
    first.next({status: 'resolved', identityId: 1, displayName: 'Theo'});
    expect(service.displayName()).toBeUndefined();
    second.next({status: 'unlinked'}); expect(service.state().status).toBe('unlinked');
    second.error(new Error('unavailable'));
    expect(service.state().status).toBe('verification_unavailable');
    expect(service.displayName()).toBeUndefined();
  });
});
