import {provideZonelessChangeDetection, signal} from '@angular/core';
import {TestBed} from '@angular/core/testing';
import {By} from '@angular/platform-browser';
import {FinanceDateInputComponent} from '../shared/finance-date-input.component';
import {ActivatedRoute, convertToParamMap, provideRouter} from '@angular/router';
import {ColumnFilter} from 'primeng/table';
import {FilterMetadata} from 'primeng/api';
import {of, Subject} from 'rxjs';
import {FinanceAccount, FinanceCounterparty, FinanceCounterpartyMergeResult} from '../../../../../generated/backend-api/thereabout';
import {FinanceContext, FinanceDialogs} from '../shared/finance-ui';
import {CounterpartyListComponent} from './counterparty-list.component';
import {TransactionsComponent} from './transactions.component';
import {CounterpartyDetailComponent} from './counterparty-detail.component';

const counterparty = (id:number):FinanceCounterparty => ({id,name:`Shop ${id}`,version:id,aliases:[`Alias ${id}`],accounts:[],active:true});

describe('Finance improvements', () => {
  const transactions=vi.fn(() => of({items:[],total:0,page:0,pageSize:50}));
  const previewResponse=new Subject<FinanceCounterpartyMergeResult>();
  const preview=vi.fn(() => previewResponse);
  const merge=vi.fn(() => of({}));
  const list=vi.fn(() => of({items:[counterparty(1)],total:51,page:0,pageSize:50}));
  const saving=signal(false);
  const details=new Subject<FinanceCounterparty>();
  const get=vi.fn(()=>details);
  const save=vi.fn();
  const context={api:{transactions,client:{financeListCounterparties:list,financePreviewCounterpartyMerge:preview,financeMergeCounterparties:merge,financeGetCounterparty:get,financeSaveCounterparty:save}},revision:signal(0),saving,error:signal(''),categories:signal([]),accounts:signal([]),money:(value:string)=>value,write:vi.fn()};
  beforeEach(() => {
    vi.clearAllMocks(); saving.set(false);
    TestBed.configureTestingModule({providers:[provideZonelessChangeDetection(),provideRouter([]),{provide:FinanceContext,useValue:context},{provide:FinanceDialogs,useValue:{open:vi.fn()}}]});
  });
  it('keeps date drafts local until Apply, rejects incomplete rules, and clears the server query', async () => {
    const fixture=TestBed.createComponent(TransactionsComponent);
    fixture.detectChanges();
    await fixture.whenStable();
    transactions.mockClear();
    const component=fixture.componentInstance;
    const rules:FilterMetadata[]=[{value:null,matchMode:'dateOnOrAfter',operator:'and'}];
    const column={fieldConstraints:rules,setHasFilter:vi.fn(),hide:vi.fn(),clearFilter:vi.fn()} as unknown as ColumnFilter;
    component.applyDates(column);
    await fixture.whenStable(); expect(transactions).not.toHaveBeenCalled();
    component.setDate(rules[0],'2026-10-01');
    rules.push({value:new Date(2026,9,7),matchMode:'dateOnOrBefore',operator:'and'});
    component.tableChanged({first:0,sortField:'occurredAt',sortOrder:-1,filters:{occurredAt:rules}});
    await fixture.whenStable(); expect(transactions).not.toHaveBeenCalled();
    component.applyDates(column);
    await fixture.whenStable();
    expect(transactions).toHaveBeenLastCalledWith(expect.objectContaining({page:0,dateFilter:{operator:'and',rules:[{mode:'dateOnOrAfter',date:'2026-10-01'},{mode:'dateOnOrBefore',date:'2026-10-07'}]}}));
    component.clearDates(column);
    await fixture.whenStable();
    expect(transactions).toHaveBeenLastCalledWith(expect.objectContaining({dateFilter:undefined}));
    expect(column.clearFilter).toHaveBeenCalledOnce();
  });
  it('retains calendar selections in the PrimeNG menu without applying the draft', async () => {
    const fixture=TestBed.createComponent(TransactionsComponent);fixture.detectChanges();await fixture.whenStable();
    transactions.mockClear();
    fixture.nativeElement.querySelector('p-columnfilter button').click();
    await fixture.whenStable();
    const date=fixture.debugElement.query(By.directive(FinanceDateInputComponent)).componentInstance as FinanceDateInputComponent;
    date.select(new Date(2026,9,6));
    await fixture.whenStable();
    expect(document.querySelector<HTMLInputElement>('[aria-label="Date rule"]')?.value).toBe('06.10.2026');
    expect(transactions).not.toHaveBeenCalled();
    const apply=[...document.querySelectorAll<HTMLButtonElement>('button')].find(button=>button.textContent?.trim()==='Apply');
    expect(apply?.disabled).toBe(false);apply!.click();
    await fixture.whenStable();
    expect(transactions).toHaveBeenLastCalledWith(expect.objectContaining({dateFilter:{operator:'and',rules:[{mode:'dateIs',date:'2026-10-06'}]}}));
  });
  it('retains selection across pages and submits only the reviewed versions and metadata', async () => {
    const fixture=TestBed.createComponent(CounterpartyListComponent);
    fixture.detectChanges();
    await fixture.whenStable();
    const component=fixture.componentInstance;
    const check=document.createElement('input');check.type='checkbox';check.checked=true;
    const event=new Event('change');Object.defineProperty(event,'target',{value:check});
    component.toggle(counterparty(1),event);component.page({first:50});
    await fixture.whenStable();
    component.toggle(counterparty(51),event);component.open();
    expect(preview).toHaveBeenCalledWith({ids:[1,51],targetId:1,name:'Shop 1',websiteUrl:''});
    expect(component.loadingPreview()).toBe(true);
    const result:FinanceCounterpartyMergeResult={counterparty:{...counterparty(1),name:'Reviewed shop'},selected:[counterparty(1),counterparty(51)],mergedIds:[51],aliases:['Shop 1','Shop 51'],affectedTransactions:24,conflicts:[]};
    previewResponse.next(result);
    await fixture.whenStable();
    expect(document.body.textContent).toContain('24 affected transactions');
    component.name='Changed after preview';component.changed();
    await component.combine();expect(context.write).not.toHaveBeenCalled();
    component.preview.set(result);
    context.write.mockResolvedValue(result);
    await component.combine();
    expect(context.write).toHaveBeenCalledWith('counterparties.merge',{ids:[1,51],targetId:1,name:'Reviewed shop',websiteUrl:undefined,versions:[{id:1,version:1},{id:51,version:51}]},expect.any(Function));
    expect(component.selected()).toEqual([]);expect(component.visible()).toBe(false);
  });
  it('shows each direction and currency once for a combined counterparty', async () => {
    const account=(id:number,kind:FinanceAccount['kind'],currency:string):FinanceAccount=>({id,name:'Shop',kind,currency,active:true,deleted:false,includeNetWorth:false,version:0,balance:'0'});
    list.mockReturnValueOnce(of({items:[{...counterparty(1),accounts:[account(1,'EXPENSE','CHF'),account(2,'EXPENSE','CHF'),account(3,'REVENUE','CHF'),account(4,'REVENUE','CHF'),account(5,'EXPENSE','EUR')]}],total:1,page:0,pageSize:50}));
    const fixture=TestBed.createComponent(CounterpartyListComponent);fixture.detectChanges();await fixture.whenStable();
    const labels=[...fixture.nativeElement.querySelectorAll('tbody .badge')].map((label:Element)=>label.textContent?.trim());
    expect(labels).toEqual(['Expense · CHF','Revenue · CHF','Expense · EUR']);
  });
  it('edits alias pills locally, prevents duplicate additions, and saves the reviewed list with its version', async () => {
    TestBed.overrideProvider(ActivatedRoute,{useValue:{paramMap:of(convertToParamMap({id:'1'})),queryParamMap:of(convertToParamMap({}))}});
    const fixture=TestBed.createComponent(CounterpartyDetailComponent);fixture.detectChanges();await fixture.whenStable();
    expect(fixture.nativeElement.querySelector('a').getAttribute('href')).toBe('/finances/accounts?view=counterparties');
    details.next({...counterparty(1),aliases:['Digitec','Galaxus']});await fixture.whenStable();
    const root:HTMLElement=fixture.nativeElement;
    expect(root.querySelectorAll('p-chip')).toHaveLength(2);
    const draft=root.querySelector<HTMLInputElement>('[aria-label="New alias"]')!;
    draft.value='  New shop alias  ';draft.dispatchEvent(new Event('input',{bubbles:true}));await fixture.whenStable();
    const enter=new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true});draft.dispatchEvent(enter);await fixture.whenStable();
    expect(enter.defaultPrevented).toBe(true);expect(context.write).not.toHaveBeenCalled();
    expect(fixture.componentInstance.aliases()).toEqual(['Digitec','Galaxus','New shop alias']);
    draft.value='New shop alias';draft.dispatchEvent(new Event('input',{bubbles:true}));await fixture.whenStable();
    const add=[...root.querySelectorAll('button')].find(button=>button.textContent?.trim()==='Add alias')!;
    expect(add.disabled).toBe(true);
    root.querySelector('[aria-label="Remove alias Galaxus"]')!.dispatchEvent(new MouseEvent('click',{bubbles:true}));await fixture.whenStable();
    expect(fixture.componentInstance.aliases()).toEqual(['Digitec','New shop alias']);
    expect(context.write).not.toHaveBeenCalled();
    context.write.mockResolvedValue(counterparty(1));
    [...root.querySelectorAll('button')].find(button=>button.textContent?.trim()==='Save changes')!.click();await fixture.whenStable();
    expect(context.write).toHaveBeenCalledWith('counterparties.save',{version:1,name:'Shop 1',websiteUrl:'',aliases:['Digitec','New shop alias']},expect.any(Function));
    saving.set(true);await fixture.whenStable();
    expect(root.querySelectorAll('p-chip [role="button"]')).toHaveLength(0);expect(draft.disabled).toBe(true);
  });
});
