springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    show-extensions: true
    show-common-extensions: true

server:
  port : 9050

spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  datasource:
    url: jdbc:mariadb://mariadb:3306/${THEREABOUT_DATABASE:thereabout}
    username: ${THEREABOUT_DB_USER:thereabout}
    password: ${THEREABOUT_DB_PASSWORD:secret}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 580000
  web:
    resources:
      static-locations: classpath:/frontend/

thereabout:
  apiKeys:
    googleMaps: ${GOOGLE_MAPS_API_KEY}
  import:
    import-folder: /data
  config:
    routing:
      frontend-path: /frontend/